name: Navi Application Build

on:
  workflow_dispatch:
  push:

jobs:
  Creating_and_Pushing_Docker_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: linslucas/navi:${{ GITHUB.RUN_NUMBER }}
          platforms: linux/amd64